enable_testing()
add_subdirectory(${CMAKE_SOURCE_DIR}/googletest ${CMAKE_BINARY_DIR}/googletest-build)
include_directories(${gtest_SOURCE_DIR}/include)
add_executable(DiagnosticService_test DiagnosticService_test.cpp)
if(MSVC)
  target_link_libraries(DiagnosticService_test gtest gtest_main diag)
else()
  target_link_libraries(DiagnosticService_test gtest gtest_main diag pthread)
endif()
add_test(NAME DiagnosticService_test COMMAND DiagnosticService_test)
