name: CI

on:
  push:
     branches: [main]
  pull_request:
     branches: [main]
jobs:
    ci:
       runs-on: windows-latest
       steps:
         - uses: action/checkouts@v2
         - uses: bazelbuild/setup-bazelisk@v3
         - run: bazel build //...
         
     
     
